---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: flux-image-updates
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flux-image-updates
  policy:
    semver:
      range: 5.0.x
