---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pod-info-mine
  namespace: flux-system
spec:
  interval: 5s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: pod-info-mine
