---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pod-info-mine
  namespace: flux-system
spec:
  interval: 5s
  ref:
    branch: new1
  secretRef:
    name: flux-system
  url: https://github.com/adilmughalqwe/pod-info-mine.git
