---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2s
  ref:
    branch: new1
  url: https://github.com/adilmughalqwe/pod-info-mine.git
