apiVersion: v1
kind: Secret
metadata:
  name: my-secret-for-flux
  namespace: default
type: Opaque
data:
  username: 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   # base64-encoded username
  password: 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   # base64-encoded password
