apiVersion: v1
kind: Secret
metadata:
  name: my-secret-for-flux
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
  username: Z2hwX2NacnduOHBIU2QyTkd6MWdtWHdRM0FUT0xsZUdwbDFwbUVXVA==   # base64-encoded username
  password: Z2hwX2NacnduOHBIU2QyTkd6MWdtWHdRM0FUT0xsZUdwbDFwbUVXVA==   # base64-encoded password
