apiVersion: v1
kind: Secret
metadata:
  name: my-secret-for-flux
  namespace: default
type: Opaque
data:
  username: Z2hwX2NacnduOHBIU2QyTkd6MWdtWHdRM0FUT0xsZUdwbDFwbUVXVA==   # base64-encoded username
  password: Z2hwX2NacnduOHBIU2QyTkd6MWdtWHdRM0FUT0xsZUdwbDFwbUVXVA==   # base64-encoded password
